development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: granny_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
